#!/bin/bash
# Deploy Velo Backend Functions to Wix
cd "$(dirname "$0")"
echo "🚀 HINGECRAFT - VELO BACKEND DEPLOYMENT"
echo ""
wix whoami
echo ""
echo "✅ All backend functions ready for deployment"
echo ""
echo "📤 Next Steps:"
echo "1. Open Wix Editor: https://editor.wix.com"
echo "2. Enable Dev Mode"
echo "3. Go to: Backend → Functions"
echo "4. Upload these files from src/backend/:"
echo "   • payment-info-service.jsw (NEW - upload first)"
echo "   • mission-support-middleware.jsw (PRIMARY)"
echo "   • stripe.api.jsw"
echo "   • nowpayments.api.jsw"
echo "   • charter-page-middleware.jsw"
echo "   • chat-notifications.jsw"
echo "   • gpt-form-config.jsw"
echo "   • receipts-hook.jsw"
echo ""
echo "📚 Wix Velo API: https://www.wix.com/velo/reference/api-overview/introduction"
