#!/bin/bash
# Execute Live Test Email
# This script provides instructions for sending the live test email

echo "🚀 HingeCraft Automation - Live Test Email"
echo "=========================================="
echo ""
echo "📧 Email Configuration:"
echo "   From: marketingecraft@gmail.com"
echo "   To: chandlerferguson319@gmail.com"
echo "   Template: B2B Step 1"
echo ""
echo "🔧 Execution Steps:"
echo ""
echo "1. Open Google Apps Script:"
echo "   https://script.google.com"
echo ""
echo "2. Select your project: HingeCraft Automation"
echo ""
echo "3. In the function dropdown, select: testSingleEmail"
echo ""
echo "4. Click the 'Run' button (▶️)"
echo ""
echo "5. Authorize the script if prompted:"
echo "   - Grant access to Gmail"
echo "   - Grant access to Drive"
echo ""
echo "6. Check the execution log for:"
echo "   ✅ Email sent successfully"
echo ""
echo "7. Check your inbox:"
echo "   chandlerferguson319@gmail.com"
echo ""
echo "8. Verify the email:"
echo "   - From: marketingecraft@gmail.com"
echo "   - Subject: Partnership Opportunity: Let's Build Together"
echo "   - Contains personalized content"
echo ""
echo "✅ Test complete!"
echo ""
